from aiostar.middleware.middlewares.downloadMiddleware.CookieMiddleware import CookieMiddleware
from aiostar.middleware.middlewares.downloadMiddleware.RequestStatMiddleware import RequestStatMiddleware
from aiostar.middleware.middlewares.downloadMiddleware.ResponseFilterMiddleware import ResponseFilterMiddleware
from aiostar.middleware.middlewares.downloadMiddleware.RetryMiddleware import RetryMiddleware
from aiostar.middleware.middlewares.downloadMiddleware.UserAgentMiddleware import UserAgentMiddleware

